// Generated by CoffeeScript 1.12.3
var Client;

Client = require('./Client');

module.exports = function(options) {
  return new Client(options);
};

module.exports.Client = Client;

module.exports.Records = require('./Records');

module.exports.Schema = require('./Schema');
